manipulator:

  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: first_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: second_joint
    pid: {p: 1000.0, i: 0.1, d: 100.0}

  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: third_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: fourth_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: fifth_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: sixth_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint8_position_controller:
    type: effort_controllers/JointPositionController
    joint: eighth_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  joint9_position_controller:
    type: effort_controllers/JointPositionController
    joint: nineth_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
